### ISSUE TITLE
Folllowing Posts にて、自分がRTした投稿の表記がおかしい

### ISSUE THREAD

**Issue by Memories-of-Sun-and-Moon** [Progate/tweet_app_for_path_intern_A_team#31]

**Comment by Memories-of-Sun-and-Moon** [comment]
[](url)
![スクリーンショット 2023-08-30 194732](https://github.com/Progate/tweet_app_for_path_intern_A_team/assets/104312078/ff254168-1636-4883-bb9d-da91307fb5d0)
自分がRTした投稿の "○○ retweeted" が、RTした投稿の主の表記になっている

**Comment by 4equest** [comment]
https://github.com/Progate/tweet_app_for_path_intern_A_team/pull/32
